/// IPTC digital source type values that may be declared by a C2PA action.
///
/// Mirrors the vocabulary c2pa_dart's `DigitalSourceType` enum exposes so the
/// public report API does not depend on c2pa_dart's types directly.
enum DigitalSourceType {
  /// Explicitly empty digital source type.
  empty,

  /// Media made from data used to train an algorithmic model.
  trainedAlgorithmicData,

  /// Media captured directly by a digital device.
  digitalCapture,

  /// Media captured through computational photography or similar processing.
  computationalCapture,

  /// Media derived from scanned negative film.
  negativeFilm,

  /// Media derived from scanned positive film.
  positiveFilm,

  /// Media derived from a scanned print.
  print,

  /// Media with minor human edits to an existing asset.
  minorHumanEdits,

  /// Media with human edits to an existing asset.
  humanEdits,

  /// Composite media containing trained algorithmic media.
  compositeWithTrainedAlgorithmicMedia,

  /// Media algorithmically enhanced from an existing asset.
  algorithmicallyEnhanced,

  /// Media generated by software rather than direct capture.
  softwareImage,

  /// Media created as digital art.
  digitalArt,

  /// Media created digitally without direct capture.
  digitalCreation,

  /// Media generated from data-driven processes.
  dataDrivenMedia,

  /// Media generated by a trained algorithmic model.
  trainedAlgorithmicMedia,

  /// Media generated by an algorithmic process.
  algorithmicMedia,

  /// Media captured from a screen display.
  screenCapture,

  /// Media recorded from a virtual environment.
  virtualRecording,

  /// Media composed from multiple sources.
  composite,

  /// Composite media that includes captured content.
  compositeCapture,

  /// Composite media that includes synthetic content.
  compositeSynthetic,

  /// Source type outside the known IPTC values.
  other,
}
